---
  - name: Update Package Manager
    apt:
      upgrade: full
      update_cache: yes
      autoremove: true

  - name: Install Docker
    shell: |
      wget -qO- https://get.docker.com | sh

  - name: Install Python3
    apt:
      name:
      - python3
      - python3-pip

  - name: Start Docker Service
    service:
      name: docker
      state: started
      enabled: yes

  - name: Install Python Docker SDK
    pip:
      name:
        - docker
        - requests

  - name: Add user to the Docker group
    shell: "usermod -aG docker {{ ansible_user }}"
    become: true